####	C	O	L	O	R	S	####
black 				=	"[1;30m"
red 				=	"[1;31m"
green 				=	"[1;32m"
yellow 				=	"[1;33m"
blue 				=	"[1;34m"
magenta 			=	"[1;35m"
cyan 				=	"[1;36m"
white 				=	"[1;37m"
####	C	O	L	O	R	S	####

all: student compile run clean

student:
	@echo $(yellow)
	@echo "Student: Omer Faruk Olkay"
	@echo "Number: 210104004039"
	@echo "mail: o.olkay2021@gtu.edu.tr"
	@echo $(white)
	@echo "The compilation has done. It will be executed in 2 seconds..."
	@echo "\n\n"
	@sleep 2

compile:
	@gcc main.c -o test

run:
	@./test

clean:
	@rm -f test