all: part1 part2

part1: queue.c
	@echo "-----------Part 1/QUEUE-----------\n"
	@echo "-----------Part 1/QUEUE-----------\n"
	@echo "-----------Part 1/QUEUE-----------\n"
	@echo "-----------Part 1/QUEUE-----------\n\n"
	@gcc -o part1 queue.c
	@./part1
	@rm -f part1

part2: stack.c
	@gcc -o part2 stack.c
	@echo "-----------Part 2/STACK-----------\n"
	@echo "-----------Part 2/STACK-----------\n"
	@echo "-----------Part 2/STACK-----------\n"
	@echo "-----------Part 2/STACK-----------\n\n"
	@./part2
	@rm -f part2