all: part1 part2 part3

part1: part1.c
	@gcc -Wall -Werror -Wextra part1.c -o part1

part2: part2.c
	@gcc -Wall -Werror -Wextra part2.c -o part2

part3: part3.c
	@gcc -Wall -Werror -Wextra part3.c -o part3

clean:
	@rm -f part1
	@rm -f part2
	@rm -f part3