all: part1 part2 part3 clean

part1:
	@gcc part1.c -o part1
	@./part1
	@echo "\n\n"

part2:
	@gcc part2.c -o part2
	@./part2
	@echo "\n\n"

part3:
	@gcc part3.c -o part3
	@./part3
	@echo "\n\n"

clean:
	@rm -f a.out
	@rm -f part1
	@rm -f part2
	@rm -f part3