####	C	O	L	O	R	S	####
black 				=	"[1;30m"
red 				=	"[1;31m"
green 				=	"[1;32m"
yellow 				=	"[1;33m"
blue 				=	"[1;34m"
magenta 			=	"[1;35m"
cyan 				=	"[1;36m"
white 				=	"[1;37m"
####	C	O	L	O	R	S	####

all: student part1 part2

student:
	@echo $(yellow)
	@echo "Student: Omer Faruk Olkay"
	@echo "Number: 210104004039"
	@echo "mail: o.olkay2021@gtu.edu.tr"
	@echo $(white)
	@echo "The compilation has done. It will be executed in 2 seconds..."
	@echo "\n\n"
	@sleep 0.5

part1:
	@echo "\n\n----------------PART 1----------------\n\n"
	@gcc part1.c -o part1
	@./part1
	@rm -f part1

part2:
	@echo "\n\n----------------PART 2----------------\n\n"
	@gcc part2.c -o part2
	@./part2
	@rm -f part2

